### ISSUE TITLE
GitHub Userscripts

### ISSUE THREAD

**Issue by Mottie** [xhacker/awesome-github-extensions#7]
## Userscripts we maintain

[GitHub-Dark-Script](https://github.com/StylishThemes/GitHub-Dark-Script)
- Applies the [GitHub-Dark](https://github.com/StylishThemes/GitHub-Dark) Stylish theme without using the Stylish addon.
- An options panel allows you to change settings on-the-fly without the need to reinstall.
- Adds a code wrap toggle button to every code block.
- Adds a monospace font toggle to comment textareas.
- Adds a diff file view toggle to collapse or expand blocks.

[GitHub-Custom-Emojis](https://github.com/StylishThemes/GitHub-Custom-Emojis)
- Adds an autocomplete method to add custom animated emojis. <img title=":_ tuzki_yesss :" src="https://cloud.githubusercontent.com/assets/136959/13203738/b38f2810-d883-11e5-9c8f-51e79116d133.gif"> 
- Adds an autocomplete method for unicode text & custom text emojis.

[GitHub-show-repo-issues](https://github.com/Mottie/Github-show-repo-issues)
- Add a repo issues count and link to the user/organization page.
- I might eventually move this script to the StylishThemes organization to keep them all together; I'll let you know if/when I do.
## Miscellaneous userscripts

[Userscripts by jerone](https://github.com/jerone/UserScripts)
- There are 10 GitHub userscripts on this page
- I used the comment enhancer script until GitHub added their own.

[Userscripts by stuartpb](https://github.com/ghes)
- There are 2 GitHub userscripts on this page.
- I use https://github.com/ghes/isaacs-github-contact-xposter, so I don't have to remember to copy the contact text when I message GitHub.

There are a bunch more on [Greasyfork](https://greasyfork.org/en/scripts/search?q=GitHub) which I have not had a chance to try out.

**Comment by xhacker** [comment]
Hi @Mottie, I’ve added two userscripts you mentioned. I don’t really want to add a list of scripts, since this repo is already a list. If you have anything new to recommend, please open an issue or simply add a pr :)
